### ISSUE TITLE
question:

### ISSUE THREAD

**Issue by csantanapr** [driftyco/ionic-app-lib#13]
I see that ionic-app-lib depends on npm package ionic-cordova-lib

Why does it depends on ionic-cordova-lib and not the Apache Cordova package cordova-lib that we release to npm?

What are the differences?

Where can I see the source code for ionic-cordova-lib? the git url points to apache git, but that can't be because at least package.json should be different with package name.

By the way I'm not a troll, I'm a Apache Cordova committer :-).

Keep the great work !!

**Comment by jbavari** [comment]
@csantanapr I have forked cordova-lib to make some small but necessary changes that we need to use the cordova-lib from other projects other than the ionic-cli. The reason we aren't using cordova-lib - we move a little bit faster and can't always wait for PRs and other changes to go down the apache channel. No other reason than that.

To be more precise, I modified the cordova-lib to pass in the `stdio` option for several commands (build, compile, create, run, etc).

Also, since we are making calls from other projects into the cordova-lib, there are portions of the lib that catch errors in a promise chain, but do not percolate them up. I had to throw the exception again for the callers waiting on the promise to have the error propagated. 

Most of those small changes you can see [here](https://github.com/driftyco/cordova-lib/commits/stdio-pipe).

**Comment by csantanapr** [comment]
Hi @jbavari for the quick response.

yep I installed both npm modules and was going thru the diffs

1. url for ionic-app-lib
Ah location is driftyco/cordova-lib  I was searching for driftyco/ionic-app-lib
Could you change the url in package.json next time you publish to npm it will make it more clear where is the source for the npm package coming from. https://github.com/driftyco/cordova-lib/blob/master/cordova-lib/package.json#L8

2. commits in master needed by ionic
Yes I see you have things that are already in apache/cordova-lb@master that we have not push yet.
It make sense to have your own fork to release faster things that are seating on master.
But also will beneficial if you can send email to cordova mailing list dev@cordova.apache.org and drop a line that you want a cordova-lib be release, this will allows to know if it needs to go out or just wait to release together with other tools related things (plugman cordova-cli)

3. changes to cordova-lib to make it more friendly to cli implementors
The changes to cordova-lib that you did for stdio and promises looks good to me to have in apache cordova-lib, so you can stop maintaining on your own out of sync.

How do you want to go about contributing those changes back to apache cordova-lib?

 or reporting those things so any ones else depending on cordova-lib (i.e. grunt, gulp plugins, other clis and tools) can benefit. 

We are also going to split cordova-lib functionality so the feedback also is useful for the new modularization. https://github.com/cordova/cordova-discuss/pull/12

**Comment by jbavari** [comment]
1. I've updated the package.json and published to npm.

2. I'm a part of the mailing list and I'm pretty familiar with the apache process. For reference, I'm the one that put together the Cordova plugins registry as you see it now. :)

3. Most of these changes are still being tested by us, and once we complete them, they will be contributed back. 

As far as how to get these changes back:

I'll submit a cleaned up PR once we roll finalize the changes as they fit in. As I stated, we are still experimenting and aren't 100% complete.

**Comment by csantanapr** [comment]
oh Nice to meet you Josh !! again I guess :-)

yes makes perfect sense, we do the same here at IBM with our MFP CLI, once we experiment and solved our immediate need, we refactor and see can be a generic solution to contribute back that helps others.
